robinhood-mvc/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using robinhood_mvc.Data;
using robinhood_mvc.Models;
using robinhood_mvc.Repo;

namespace robinhood_mvc.Controllers;

[Authorize]
public class CourseController : Controller
{
    private readonly CourseRepo _courseRepo;

    public CourseController(RobinhoodContext context) { _courseRepo = new CourseRepo(context); }

    public IActionResult Index() { return View(_courseRepo.GetAll()); }

    [HttpGet]
    public IActionResult Create() { return View(); }

    [HttpPost]
    public IActionResult Create(Course course)
    {
        _courseRepo.Create(course);
        return RedirectToAction("Index");
    }

    [HttpGet("Course/{id:int}")]
    public IActionResult Get(int id)
    {
        var course = _courseRepo.Get(id);
        return View(course);
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var course = _courseRepo.Get(id);
        return View(course);
    }
    
    [HttpPost]
    public IActionResult Edit(Course course)
    {
        _courseRepo.Edit(course);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        _courseRepo.Delete(id);
        return RedirectToAction("Index");
    }
}

robinhood-mvc/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using robinhood_mvc.Data;
using robinhood_mvc.Models;
using robinhood_mvc.Repo;

namespace robinhood_mvc.Controllers;

[Authorize]
public class InstructorController : Controller
{
    private readonly InstructorRepo _instructorRepo;

    public InstructorController(RobinhoodContext context) { _instructorRepo = new InstructorRepo(context); }

    public IActionResult Index() { return View(_instructorRepo.GetAll()); }

    [HttpGet]
    public IActionResult Create() { return View(); }

    [HttpPost]
    public IActionResult Create(Instructor instructor)
    {
        _instructorRepo.Create(instructor);
        return RedirectToAction("Index");
    }

    [HttpGet("Instructor/{id:int}")]
    public IActionResult Get(int id)
    {
        var instructor = _instructorRepo.Get(id);
        return View(instructor);
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var instructor = _instructorRepo.Get(id);
        return View(instructor);
    }
    
    [HttpPost]
    public IActionResult Edit(Instructor instructor)
    {
        _instructorRepo.Edit(instructor);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        _instructorRepo.Delete(id);
        return RedirectToAction("Index");
    }
}

robinhood-mvc/Controllers/PreviousController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using robinhood_mvc.Data;
using robinhood_mvc.Models;
using robinhood_mvc.Repo;

namespace robinhood_mvc.Controllers;

[Authorize]
public class PreviousController : Controller
{
    private readonly PreviousRepo _previousRepo;

    public PreviousController(RobinhoodContext context) { _previousRepo = new PreviousRepo(context); }

    public IActionResult Index() { return View(_previousRepo.GetAll()); }

    [HttpGet]
    public IActionResult Create() { return View(); }

    [HttpPost]
    public IActionResult Create(Previous previous)
    {
        _previousRepo.Create(previous);
        return RedirectToAction("Index");
    }

    [HttpGet("Previous/{id:int}")]
    public IActionResult Get(int id)
    {
        var instructor = _previousRepo.Get(id);
        return View(instructor);
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var instructor = _previousRepo.Get(id);
        return View(instructor);
    }
    
    [HttpPost]
    public IActionResult Edit(Previous previous)
    {
        _previousRepo.Edit(previous);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        _previousRepo.Delete(id);
        return RedirectToAction("Index");
    }
}

robinhood-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>@ViewData["Title"] - Robinhood</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
	<link rel="stylesheet" href="~/robinhood-mvc.styles.css" asp-append-version="true"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>
<body>
<header>
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
		<div class="container-fluid">
			<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Robinhood</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
			        aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
				<ul class="navbar-nav flex-grow-1">
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Previous" asp-action="Index">Previouses</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
					</li>
				</ul>
				<partial name="_LoginNavbar"/>
			</div>
		</div>
	</nav>
</header>
<div class="container">
	<main role="main" class="pb-3">
		@RenderBody()
	</main>
</div>

<footer class="border-top footer text-muted">
	<div class="container">
		&copy; 2022 - Robinhood
	</div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

robinhood-mvc/Views/Shared/_LoginNavbar.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager;

<ul class="navbar-nav">
	@if (SignInManager.IsSignedIn(User))
	{
		<li class="nav-item">
			<form asp-action="LogOut"
			      asp-controller="Account"
			      method="Post">
				<input class="btn btn-outline-dark" type="submit" value="Log Out"/>
				<span class="text-dark">@User.Identity.Name</span>
			</form>
		</li>
	}
	else
	{
		<li class="nav-item">
			<a asp-action="Register"
			   asp-controller="Account"
			   class="nav-link">Register</a>
		</li>
		<li>
			<a asp-action="LogIn"
			   asp-controller="Account"
			   class="nav-link btn btn-outline-dark">Log in</a>
		</li>
	}
</ul>